Repository softeerbootcamp-6th/fe-1, pull requests merged in 2025-07, with the labels that each got.

#31 [시보성] - 인풋바 전체 골격 생성 및 컴포넌트화 & date data 객체 생성
  README.md
  components/header/index.css
  components/header/index.js
  components/inputbar/index.css
  components/inputbar/index.js
  components/inputbar/inputItems/category.js
  components/inputbar/inputItems/date.js
  components/inputbar/inputItems/description.js
  components/inputbar/inputItems/payment.js
  components/inputbar/inputItems/value.js
  components/inputbar/summitBtn.js
  index.html
  index.js
  main.css
  reset.css
  store/date.js
  utils.js
Labels: 메인-내역입력, 공통코드, 메인-헤더영역

#33 [이종우] - 구현 및 스타일링 개선을 포함한 InputBar 컴포넌트 개발
  README.md
  calendar.html
  chart.html
  components/Header/index.css
  components/Header/index.html
  components/Header/index.js
  components/InputBar/InputItems/amount.js
  components/InputBar/InputItems/category.js
  components/InputBar/InputItems/content.js
  components/InputBar/InputItems/date.js
  components/InputBar/InputItems/paymentMethod.js
  components/InputBar/index.css
  components/InputBar/index.js
  components/InputBar/submitButton.js
  index.html
  lib/utils.js
  styles/globals.css
Labels: 리팩토링, 메인-내역입력, 공통코드

#39 [홍규진] - 메인 페이지 기능 구현 및 함수 기능별 관심사 분리
  assets/icons/delete.svg
  assets/icons/icons/Check.svg
  index.css
  index.html
  index.js
  src/constants/dummy.js
  src/layouts/headers/header-rendering.js
  src/layouts/headers/header.html
  src/layouts/headers/header.js
  src/styles/fonts.css
  src/utils/dataUtils.js
  src/utils/dateUtils.js
  src/utils/formatUtils.js
  src/utils/uiUtils.js
Labels: 리팩토링, 메인-내역입력, 메인-수입지출목록, 메인-헤더영역

#42 [김미소] - 메인페이지 입력바 개발 진행 중
  .github/workflows/merge.yml
  assets/icons/check-button-active.svg
  assets/icons/check-button.svg
  assets/icons/minus.svg
  assets/icons/plus.svg
  global.css
  src/App.js
  src/components/DropDown/DropDown.js
  src/components/DropDown/DropDownBlock.js
  src/index.js
  src/layout/Header.js
  src/pages/MainPage/MainPage.css
  src/pages/MainPage/MainPage.js
  src/pages/MainPage/components/InputBar.js
Labels: 메인-내역입력, 공통코드

#53 [이종우] - 월별 가계부 목록 뷰 및 상세 내역 UI 구현
  README.md
  assets/icons/closed.red.svg
  components/DailyInfo/DetailList/index.js
  components/DailyInfo/DetailListItem/categoryConfig.js
  components/DailyInfo/DetailListItem/index.js
  components/DailyInfo/List/index.js
  components/DropdownOption/index.js
  components/Header/index.js
  components/InputBar/InputItems/amount.js
  components/InputBar/InputItems/category.js
  components/InputBar/InputItems/content.js
  components/InputBar/InputItems/date.js
  components/InputBar/InputItems/paymentMethod.js
  components/InputBar/index.css
  components/InputBar/index.js
  components/InputBar/submitButton.js
  components/MonthlyInfo/index.js
  index.html
  js/mainpage.js
  lib/datas/monthlyInfoDummyData.js
  lib/utils.js
  main.js
  monthlyInfo.css
Labels: 리팩토링, 메인-수입지출목록

#55 [김미소] - 메인페이지 수입지출내역 구현 중
  assets/icons/check-btn-square.svg
  global.css
  src/components/DailyListBlock/DailyListBlock.js
  src/components/DropDown/DropDown.js
  src/components/TagBox/TagBox.js
  src/pages/MainPage/MainPage.css
  src/pages/MainPage/MainPage.js
  src/pages/MainPage/components/DailyList.js
  src/pages/MainPage/components/InputBar.js
Labels: 메인-내역입력, 공통코드, 메인-수입지출목록

#54 [시보성]- inputbar와 date, formdata Store & 이벤트 리스너 생성
  components/header/index.js
  components/inputbar/index.css
  components/inputbar/inputItems/category.js
  components/inputbar/inputItems/date.js
  components/inputbar/inputItems/description.js
  components/inputbar/inputItems/payment.js
  components/inputbar/inputItems/value.js
  components/inputbar/summitBtn.js
  store/date.js
  store/formData.js
Labels: 메인-내역입력, 공통코드

#51 [유재민] - 유효성 검사 로직 추가 및 분류 조건부 렌더링 구현
  README.md
  assets/main.css
  pages/main.html
  scripts/elements.js
  scripts/index.js
  scripts/input.js
Labels: 리팩토링, 메인-내역입력, 문서화

#43 [배연준] - 7/11 main 레이아웃 제작 완료
  softeer_1st/assets/dummy.json
  softeer_1st/assets/icons/check-white.svg
  softeer_1st/components/CostList.js
  softeer_1st/components/DatesCard.js
  softeer_1st/components/Form.js
  softeer_1st/pages/renderMain.js
  softeer_1st/styles/reset.css
  softeer_1st/styles/style.css
Labels: 메인-내역입력, 메인-수입지출목록

#44 [소보길] - 코드 리팩토링과 css적용 및 지출추가 기능 구현
  assets/fonts/PretendardVariable.woff2
  assets/icons/black-check.svg
  assets/icons/calendar.svg
  assets/icons/chart.svg
  assets/icons/check.svg
  assets/icons/checkbox.svg
  assets/icons/chevron-down.svg
  assets/icons/chevron-left.svg
  assets/icons/chevron-right.svg
  assets/icons/chevron-up.svg
  assets/icons/closed.svg
  assets/icons/delete.svg
  assets/icons/doc.svg
  assets/icons/logo.svg
  assets/icons/minus.svg
  assets/icons/plus.svg
  assets/icons/uncheckbox.svg
  components/header.html
  components/input-form.html
  css/colors.css
  css/fonts.css
  css/header.css
  css/input-form.css
  css/style.css
  index.html
  js/dummy.js
  js/dummy/dummy.js
  js/function/categoryRender.js
  js/function/input-form.js
  js/function/totalAmount.js
  js/index.js
  js/input-form.js
  js/listener/totalListener.js
  js/state/state.js
Labels: 리팩토링, 공통코드, 메인-수입지출목록, 메인-헤더영역

#45 [조은진] - 내역 추가, 삭제, 월 별 필터링 기능 구현
  README.md
  components/header.js
  components/inputBar.js
  components/monthlyInfo.js
  index.js
  pages.js
  store/transactionsStore.js
  styles.css
  utils/currentDate.js
  utils/routes.js
  utils/transaction.js
Labels: 메인-내역입력, 메인-수입지출목록

#46 [최지애] - dateState 적용 및 지출수입내역 입력폼 html, css 작업
  .gitignore
  README.md
  components/Header.js
  components/IncomeExpenseForm.js
  components/IncomeExpenseList.js
  main.js
  states/DateState.js
  styles/header.css
  styles/layout.css
Labels: 메인-수입지출목록, 메인-헤더영역

#47 [박종성] - 하나의 js파일을 여러 개로 나누며 모듈화, 더미 데이터 사용
  README.md
  data/dummy.json
  index.css
  index.html
  index.js
  js/categories.js
  js/date-nav.js
  js/form-validate.js
  js/main.js
  js/modal.js
  js/summary.js
Labels: 리팩토링, 메인-내역입력, 메인-수입지출목록

#48 [김민정] - 내역입력 컴포넌트 구현
  src/assets/expense.png
  src/assets/income.png
  src/components/form/CategoryForm.js
  src/components/form/ContentForm.js
  src/components/form/DateForm.js
  src/components/form/DropDown.js
  src/components/form/EntireForm.js
  src/components/form/FormChecker.js
  src/components/form/MoneyForm.js
  src/components/form/PaymentForm.js
  src/constants/category.js
  src/constants/month.js
  src/pages/Layout.js
  src/styles/global.css
  src/styles/main.css
  src/utils/handleDate.js
Labels: 메인-내역입력, 문서화

#56 [홍규진] - store을 활용한 상태관리 기법 도입 + 통계 페이지 일부 구현
  index.html
  package-lock.json
  package.json
  src/constants/dummy.js
  src/layouts/headers/header-uiUtils.js
  src/layouts/headers/header.js
  src/pages/calendar/calendar.js
  src/pages/main/main-rendering.js
  src/pages/main/main-uiUtils.js
  src/pages/main/main.css
  src/pages/main/main.js
  src/pages/statistic/statistic-rendering.js
  src/pages/statistic/statistic.css
  src/pages/statistic/statistic.js
  src/store/account-book-store.js
  src/utils/dataUtils.js
Labels: 통계화면, 리팩토링

#57 [시보성] - 데일리 리스트 생성 및 버튼 클릭시 추가 기능
  README.md
  components/dailyList/daily.js
  components/dailyList/dailyList.js
  components/dailyList/index.css
  components/dailyList/index.js
  components/header/centerNavigation.js
  components/header/headerTab.js
  components/header/index.js
  components/inputbar/index.js
  components/inputbar/inputItems/amount.js
  components/inputbar/inputItems/category.js
  components/inputbar/inputItems/date.js
  components/inputbar/inputItems/description.js
  components/inputbar/inputItems/payment.js
  components/inputbar/summitBtn.js
  data/DailyInfo.json
  index.html
  index.js
  main.css
  store/daily.js
  utils.js
Labels: 메인-내역입력, 공통코드, 메인-수입지출목록

#60 [조은진] - 스타일링 적용, 지출 및 수입 필터링 시 건수 업데이트 기능 구현
  README.md
  components/header.js
  components/inputBar.js
  components/monthlyInfo.js
  components/transactionsList.js
  constants/categoryName.js
  index.html
  pages.js
  styles.css
  utils/format.js
Labels: 리팩토링, 메인-내역입력, 공통코드, 메인-수입지출목록

#62 [유재민] - 내역 렌더링 및 항목 추가 구현, 헤더와 데이터 연결
  assets/header.css
  assets/main.css
  components/header.html
  pages/main.html
  scripts/elements.js
  scripts/header.js
  scripts/index.js
  scripts/input.js
  scripts/records.js
Labels: 리팩토링, 메인-수입지출목록

#63 [정연주] - 렌더링 구조 리팩토링, 내역 입력 기능 구현
  index.html
  public/fonts/PretendardVariable.woff2
  src/assets/icons/check.svg
  src/assets/icons/minus.svg
  src/assets/icons/plus.svg
  src/components/Header.js
  src/components/TransactionForm.js
  src/components/TransactionList.js
  src/components/transactionform.css
  src/constants/categories.js
  src/index.js
  src/store.js
  src/styles/colors.css
  src/styles/fonts.css
  src/styles/global.css
  src/utils/addEvent.js
  src/utils/date.js
  src/utils/render.js
  styles.css
Labels: 리팩토링, 메인-내역입력

#65 [최지애] - 수입 지출 form 유효성 검사 및 데이터 입력 기능 작성 중
  README.md
  assets/icons/add-button.svg
  components/IncomeExpenseForm.js
  components/IncomeExpenseList.js
  data/incomeExpenseData.js
  index.html
  states/DateState.js
  styles/colors.css
  styles/form.css
  styles/layout.css
Labels: 리팩토링, 메인-내역입력

#66 [김민정] - 내역입력 완료 및 수입지출목록 레이아웃+필터링 구현
  README.md
  index.html
  src/assets/check.png
  src/assets/check.svg
  src/assets/closed.png
  src/assets/closed.svg
  src/components/form/CategoryForm.js
  src/components/form/ContentForm.js
  src/components/form/DateForm.js
  src/components/form/DropDown.js
  src/components/form/FormChecker.js
  src/components/form/MoneyForm.js
  src/components/form/PaymentForm.js
  src/components/form/index.js
  src/components/list/DateList.js
  src/components/list/ListItem.js
  src/components/list/ListTypeFilter.js
  src/components/list/index.js
  src/components/modal/index.js
  src/constants/date.js
  src/index.js
  src/mocks/DummyList.js
  src/pages/Calendar.js
  src/pages/Chart.js
  src/pages/Doc.js
  src/pages/Header.js
  src/pages/Layout.js
  src/pages/Main.js
  src/router.js
  src/styles/global.css
  src/styles/header.css
  src/styles/main.css
  src/styles/reset.css
  src/utils/DateManager.js
  src/utils/ElementManager.js
  src/utils/InputValidator.js
  src/utils/ListFilter.js
  src/utils/NumberManager.js
  src/utils/Router.js
  src/utils/handleDate.js
Labels: 리팩토링, 메인-내역입력, 메인-수입지출목록, 문서화

#69 [이종우] Modal 컴포넌트 구현 및 incomeMode Custom Event 생성
  README.md
  components/InputBar/InputItems/amount.js
  components/InputBar/InputItems/category.js
  components/InputBar/InputItems/paymentMethod.js
  components/InputBar/index.js
  components/Modal/index.js
  index.html
  store/form.js
  styles/modal.css
Labels: 리팩토링, 메인-내역입력

#71 [배연준]-main화면, 캘린더 화면 완성. Stats 진행중
  backend/data.json
  backend/server.js
  softeer_1st/api/api.js
  softeer_1st/components/CalenderDate.js
  softeer_1st/components/CostList.js
  softeer_1st/components/DatesCard.js
  softeer_1st/components/DonutChart.js
  softeer_1st/components/DonutGraph.js
  softeer_1st/components/Form.js
  softeer_1st/index.html
  softeer_1st/pages/renderCalender.js
  softeer_1st/pages/renderMain.js
  softeer_1st/pages/renderStats.js
  softeer_1st/router.js
  softeer_1st/styles/calender.css
  softeer_1st/styles/header.css
  softeer_1st/styles/main.css
  softeer_1st/styles/stats.css
  softeer_1st/styles/style.css
Labels: 캘린더화면, 통계화면, 리팩토링, 메인-내역입력, 메인-수입지출목록

#72 [시보성] - 월별 리렌더링 및 수입/지출 필터 기능 완료
  components/dailyList/daily.js
  components/dailyList/dailyList.js
  components/dailyList/index.css
  components/dailyList/index.js
  components/header/centerNavigation.js
  components/inputbar/inputItems/amount.js
  components/inputbar/summitBtn.js
  store/daily.js
  store/formData.js
  utils.js
Labels: 공통코드, 메인-수입지출목록

#73 [최지애] 수입 지출 내역 추가 및 수입 지출 내역 리스트 UI 작성
  components/Header.js
  components/IncomeExpenseForm.js
  components/IncomeExpenseList.js
  data/incomeExpenseData.js
  data/incomeExpenseData.json
  index.html
  main.js
  store/dateStore.js
  store/store.js
  styles/layout.css
  styles/list.css
Labels: 리팩토링, 메인-내역입력, 공통코드, 메인-수입지출목록

#74 [조은진] - 수정 기능, 캘린더 구현
  components/calendar.js
  components/inputBar.js
  components/monthlyInfo.js
  components/transactionsList.js
  constants/category.js
  pages.js
  store/transactionsStore.js
  styles.css
  utils/currentDate.js
  utils/transaction.js
Labels: 캘린더화면, 리팩토링, 메인-내역입력

#76 [김민정] - 전역 이벤트 관리자 도입 및 수입지출 업데이트시 무한재귀 문제 고민
  src/assets/closed_white.svg
  src/components/form/CategoryForm.js
  src/components/form/ContentForm.js
  src/components/form/DateForm.js
  src/components/form/DropDown.js
  src/components/form/FormChecker.js
  src/components/form/MoneyForm.js
  src/components/form/PaymentForm.js
  src/components/form/index.js
  src/components/list/DateList.js
  src/components/list/ListItem.js
  src/components/list/ListTypeFilter.js
  src/index.js
  src/store/EventBusStore.js
  src/store/ListStore.js
  src/styles/main.css
  src/utils/ListFilter.js
Labels: 리팩토링, 메인-내역입력, 공통코드, 메인-수입지출목록, 문서화

#79 [김미소] - 날짜에 따라 수입지출목록 업데이트
  mock/DummyData.json
  src/App.js
  src/components/DailyListBlock/DailyListBlock.js
  src/layout/Header.js
  src/pages/MainPage/MainPage.css
  src/pages/MainPage/MainPage.js
  src/pages/MainPage/components/DailyList.js
  src/pages/MainPage/components/InputBar.js
  src/utils/calculate.js
  src/utils/format.js
  store/incomeExpenseStore.js
Labels: 리팩토링, 메인-내역입력, 공통코드, 메인-수입지출목록

#86 [이종우] - 결제 내역 구조 및 상태 관리 개선, 모달 삭제 기능 추가
  README.md
  components/DailyInfo/DetailList/index.js
  components/DailyInfo/DetailListItem/index.js
  components/DailyInfo/List/index.js
  components/DropdownOption/index.js
  components/Header/index.css
  components/Header/index.js
  components/InputBar/InputItems/content.js
  components/InputBar/InputItems/description.js
  components/InputBar/InputItems/paymentMethod.js
  components/InputBar/index.css
  components/InputBar/index.js
  components/MonthlyInfo/index.js
  js/mainpage.js
  lib/datas/monthlyInfoDummyData.js
  lib/utils.js
  monthlyInfo.css
  store/date.js
  store/form.js
  store/paymentData.js
Labels: 리팩토링, 메인-내역입력, 공통코드, 메인-수입지출목록, 메인-헤더영역

#87 [박종성] - 가계부의 세부내역을 클릭하면 폼으로 불러오고 수정 구현
  data/dummy.json
  src/app/main.js
  src/app/store.js
  src/domains/entryForm/ui/formView.js
  src/domains/summary/ui/summaryView.js
  src/shared/components/modal.js
  src/shared/constants/jsonServerUrl.js
  src/shared/data/dummyData.js
  src/shared/data/initDummyData.js
Labels: 리팩토링, 메인-내역입력, 공통코드, 메인-수입지출목록

#89 [조은진] - store 구현 및 옵저버 패턴 적용, 도넛 차트 구현 (진행중)
  README.md
  calendar/index.html
  chart/index.html
  components/calendar.js
  components/chart.js
  components/header.js
  components/inputBar.js
  components/monthlyInfo.js
  components/transactionsList.js
  constants/category.js
  data/transactionsData.json
  index.js
  pages.js
  pages/calendarPage.js
  pages/chartPage.js
  pages/mainPage.js
  store/dateStore.js
  store/index.js
  store/observer.js
  store/transactionStore.js
  store/transactionsStore.js
  styles.css
  utils/currentDate.js
  utils/routes.js
  utils/style.js
  utils/transaction.js
Labels: 통계화면, 리팩토링, 공통코드

#93 [김민정] - 디스패처 패턴 기반 수입지출목록 Store 구현
  README.md
  src/components/form/CategoryForm.js
  src/components/form/ContentForm.js
  src/components/form/DateForm.js
  src/components/form/FormChecker.js
  src/components/form/MoneyForm.js
  src/components/form/PaymentForm.js
  src/components/form/index.js
  src/components/list/DateList.js
  src/components/list/ListItem.js
  src/components/list/ListTypeFilter.js
  src/components/list/index.js
  src/index.js
  src/mocks/DummyList.js
  src/pages/Header.js
  src/pages/Layout.js
  src/store/DateStore.js
  src/store/FormStore.js
  src/store/ListStore.js
  src/store/Store.js
  src/styles/main.css
  src/utils/DateManager.js
  src/utils/EventDispatcher.js
  src/utils/InputValidator.js
  src/utils/ListFilter.js
Labels: 리팩토링, 메인-내역입력, 메인-수입지출목록, 문서화

#94 [정연주] - 옵저버 등록, 메인 영역에 반영
  index.html
  src/actions/headerActions.js
  src/assets/icons/closed.svg
  src/components/Header.js
  src/components/HeaderView.js
  src/components/TransactionForm.js
  src/components/TransactionList.js
  src/components/transactionFormView.js
  src/components/transactionList.css
  src/components/transactionform.css
  src/observers/headerObserver.js
  src/observers/transactionFormObservers.js
  src/pages/main.js
  src/store/DateState.js
  src/store/FormState.js
  src/store/ItemsState.js
  src/store/NavBarState.js
  src/store/Observable.js
Labels: 메인-내역입력, 공통코드, 메인-헤더영역

#96 [이종우] - form component 생성 및 내역 수정 기능 및 날짜 기준으로 데이터 표시, 캘린더 페이지 생성, router 부분 구현
  README.md
  calendar.html
  chart.html
  components/Calendar/index.css
  components/Calendar/index.js
  components/Checkbox/index.css
  components/Checkbox/index.js
  components/DailyInfo/DetailListItem/index.js
  components/DailyInfo/index.css
  components/DropdownOption/index.css
  components/DropdownOption/index.js
  components/Form/index.js
  components/Header/index.css
  components/Header/index.js
  components/InputBar/InputItems/amount.js
  components/InputBar/InputItems/category.js
  components/InputBar/InputItems/date.js
  components/InputBar/InputItems/description.js
  components/InputBar/InputItems/paymentMethod.js
  components/InputBar/index.css
  components/InputBar/index.js
  components/Modal/index.css
  components/Modal/index.js
  components/MonthlyInfo/index.js
  components/TotalAmountInfo/index.css
  components/TotalAmountInfo/index.js
  index.html
  js/calendarPage.js
  js/main.js
  js/mainpage.js
  js/router.js
  lib/constant.js
  lib/utils.js
  store/date.js
  store/paymentData.js
  styles/animations.css
Labels: 캘린더화면, 리팩토링, 메인-내역입력, 공통코드, 메인-수입지출목록, 메인-헤더영역

#101 [홍규진] - 각 페이지 Component로 분리 & 로딩 프로세스 추가 & 차트 에니메이팅 추가
  index.html
  src/layouts/loading/loading-rendering.js
  src/layouts/loading/loading.css
  src/layouts/modal/modal-rendering.js
  src/layouts/modal/modal.css
  src/layouts/modal/modal.js
  src/pages/calendar/calendar-rendering.js
  src/pages/calendar/calendar.js
  src/pages/calendar/components/cell/cell-handlers.js
  src/pages/calendar/components/cell/cell-rendering.js
  src/pages/calendar/components/summary/summary-handlers.js
  src/pages/calendar/components/summary/summary-rendering.js
  src/pages/main/components/dropdown/dropdown-handlers.js
  src/pages/main/components/dropdown/dropdown-rendering.js
  src/pages/main/components/history/history-handlers.js
  src/pages/main/components/history/history-rendering.js
  src/pages/main/components/input/input-handlers.js
  src/pages/main/components/input/input-rendering.js
  src/pages/main/components/summary/summary-handlers.js
  src/pages/main/components/summary/summary-rendering.js
  src/pages/main/main-rendering.js
  src/pages/main/main-ui-utils.js
  src/pages/main/main.css
  src/pages/main/main.js
  src/pages/main/utils/form-utils.js
  src/pages/main/utils/main-ui-utils.js
  src/pages/statistic/components/category/category-handlers.js
  src/pages/statistic/components/category/category-rendering.js
  src/pages/statistic/components/donut-chart/donut-chart-handlers.js
  src/pages/statistic/components/donut-chart/donut-chart-rendering.js
  src/pages/statistic/components/history/history-handlers.js
  src/pages/statistic/components/history/history-rendering.js
  src/pages/statistic/components/trend/trend-handlers.js
  src/pages/statistic/components/trend/trend-rendering.js
  src/pages/statistic/constants/category-colors.js
  src/pages/statistic/statistic-rendering.js
  src/pages/statistic/statistic.css
  src/pages/statistic/statistic.js
  src/store/routing-store.js
  src/store/transaction-store.js
  src/utils/data-utils.js
  src/utils/date-utils.js
Labels: 통계화면, 리팩토링, 공통코드

#104 [김민정] - 전역 상태 관리자 구현 및 서버 상태 관리 캐시 도입
  README.md
  package-lock.json
  package.json
  src/api/ListApi.js
  src/components/form/FormChecker.js
  src/components/form/PaymentForm.js
  src/components/list/ListItem.js
  src/components/list/ListTypeFilter.js
  src/components/list/index.js
  src/components/modal/index.js
  src/mocks/DummyList.js
  src/mocks/db.json
  src/pages/Doc.js
  src/pages/Layout.js
  src/store/ListStore.js
  src/store/Store.js
  src/styles/global.css
  src/styles/main.css
  src/utils/CacheManager.js
  src/utils/EventDispatcher.js
  src/utils/ListFilter.js
  src/utils/NumberManager.js
  src/utils/Timer.js
Labels: 리팩토링, 메인-내역입력, 공통코드, 메인-수입지출목록

#106 [정연주] - 폴더 구조 정리, 옵저버 리팩토링, 메인 영역 API 연결, 메인 영역 필터링 기능 추가, 캘린더 추가
  .gitignore
  index.html
  package-lock.json
  package.json
  src/actions/headerActions.js
  src/apis/items.js
  src/apis/method.js
  src/assets/icons/checkbox.svg
  src/assets/icons/uncheckbox.svg
  src/components/Header.js
  src/components/TransactionForm.js
  src/components/TransactionList.js
  src/components/calendar/CalendarController.js
  src/components/calendar/CalendarView.js
  src/components/calendar/calendar.css
  src/components/header/HeaderController.js
  src/components/header/HeaderEvents.js
  src/components/header/HeaderView.js
  src/components/header/header.css
  src/components/transaction-form/TransactionFormController.js
  src/components/transaction-form/TransactionFormEvents.js
  src/components/transaction-form/TransactionFormView.js
  src/components/transaction-form/transactionform.css
  src/components/transaction-list/TransactionListController.js
  src/components/transaction-list/TransactionListEvents.js
  src/components/transaction-list/TransactionListView.js
  src/components/transaction-list/transactionlist.css
  src/components/transactionFormView.js
  src/constants/baseUrl.js
  src/controllers/headerController.js
  src/index.js
  src/observers/TransactionListObserver.js
  src/observers/calendarObserver.js
  src/observers/headerObserver.js
  src/observers/layoutObserver.js
  src/observers/transactionFormObservers.js
  src/pages/calendar.js
  src/pages/main.js
  src/store.js
  src/store/DateState.js
  src/store/FilterState.js
  src/store/FormState.js
  src/store/ItemsState.js
  src/store/NavBarState.js
  src/store/data.json
  src/utils/addEvent.js
  src/utils/date.js
  src/utils/render.js
Labels: 캘린더화면, 리팩토링, 메인-내역입력, 공통코드, 메인-수입지출목록, 메인-헤더영역

#107 [유재민] - prototype 이용해서 observer 상속 구현 / document fragment 이용한 코드 리팩토링 / 캘린더 데이터 연동
  assets/main.css
  pages/calander.html
  scripts/api/recordsApi.js
  scripts/calander/calanderUtils.js
  scripts/elements.js
  scripts/form/formUtils.js
  scripts/header.js
  scripts/index.js
  scripts/input.js
  scripts/records.js
  scripts/records/recordRender.js
  scripts/records/recordUtils.js
  scripts/router.js
  scripts/sayHello.js
  scripts/state/filterState.js
  scripts/state/formState.js
  scripts/store.js
  scripts/subscribe.js
  store/dateStore.js
  store/observer.js
  store/recordStore.js
  store/subscribe.js
Labels: 캘린더화면, 리팩토링, 공통코드, 메인-수입지출목록, 문서화

#108 [김미소] - 수입지출내역 수정 및 필터링 구현, 드롭다운 커스텀 구현
  assets/icons/check_btn_squre_cancelled.svg
  assets/icons/chevron-down.svg
  assets/icons/closed.svg
  global.css
  mock/DummyData.json
  src/components/DailyListBlock/DailyListBlock.js
  src/components/DropDown/DropDown.js
  src/components/DropDown/DropDownBlock.js
  src/components/TagBox/TagBox.js
  src/components/modal/Modal.css
  src/components/modal/Modal.js
  src/components/modal/ModalContent.js
  src/layout/Header.js
  src/pages/MainPage/MainPage.css
  src/pages/MainPage/MainPage.js
  src/pages/MainPage/components/DailyList.js
  src/pages/MainPage/components/InputBar.js
  src/pages/MainPage/utils/inputElementUtils.js
  src/pages/MainPage/utils/validationUtils.js
  src/store/incomeExpenseStore.js
  src/store/paymentStore.js
Labels: 메인-내역입력, 메인-수입지출목록
